//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.12.27 at 11:18:15 PM EET 
//


package fci.cu.std.paas.api.xml.services.persistent.storage;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import fci.cu.std.paas.api.xml.manifest.*;


/**
 * <p>Java class for storage_service_type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="storage_service_type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="storId" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="storage_account" type="{http://www.example.org/storageservice}storage_account"/>
 *         &lt;element name="container" type="{http://www.example.org/storageservice}container"/>
 *         &lt;element name="blob" type="{http://www.example.org/storageservice}blob"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "storage_service_type", propOrder = {
    "storId",
    "description",
    "storageAccount",
    "container",
    "blob"
})
public class StorageServiceType {

    protected int storId;
    @XmlElement(required = true)
    protected String description;
    @XmlElement(name = "storage_account", required = true)
    protected StorageServiceAccount storageAccount;
    @XmlElement(required = true)
    protected Container container;
    @XmlElement(required = true)
    protected Blob blob;

    /**
     * Gets the value of the storId property.
     * 
     */
    public int getStorId() {
        return storId;
    }

    /**
     * Sets the value of the storId property.
     * 
     */
    public void setStorId(int value) {
        this.storId = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the storageAccount property.
     * 
     * @return
     *     possible object is
     *     {@link StorageAccount }
     *     
     */
    public StorageServiceAccount getStorageAccount() {
        return storageAccount;
    }

    /**
     * Sets the value of the storageAccount property.
     * 
     * @param value
     *     allowed object is
     *     {@link StorageAccount }
     *     
     */
    public void setStorageAccount(StorageServiceAccount value) {
        this.storageAccount = value;
    }

    /**
     * Gets the value of the container property.
     * 
     * @return
     *     possible object is
     *     {@link Container }
     *     
     */
    public Container getContainer() {
        return container;
    }

    /**
     * Sets the value of the container property.
     * 
     * @param value
     *     allowed object is
     *     {@link Container }
     *     
     */
    public void setContainer(Container value) {
        this.container = value;
    }

    /**
     * Gets the value of the blob property.
     * 
     * @return
     *     possible object is
     *     {@link Blob }
     *     
     */
    public Blob getBlob() {
        return blob;
    }

    /**
     * Sets the value of the blob property.
     * 
     * @param value
     *     allowed object is
     *     {@link Blob }
     *     
     */
    public void setBlob(Blob value) {
        this.blob = value;
    }

}
