//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.12.26 at 04:34:08 AM EET 
//


package fci.cu.std.paas.api.xml.manifest;

import java.net.URI;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for blob complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="blob">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="location" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "blob")
public class Blob {

    @XmlAttribute(name = "name")
    protected String name;
    @XmlAttribute(name = "location")
    protected String location;
    
    /**
     * this var will be used to store the URI of the uploaded blob after the uploading
     * process succeed
     */
    protected URI uploadURI;
    /**
     * this var will be used to store the cloud blob object after it is created
     * its type is Object--> to be generic and it can be casted to a specific type
     * this object will be used later to upload the blob
     */
    protected Object physicalBlob;
    protected Object uploadedBlob;
    
    protected String sCType;
    

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the location property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLocation() {
        return location;
    }

    /**
     * Sets the value of the location property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLocation(String value) {
        this.location = value;
    }

	public URI getUploadURI() {
		return uploadURI;
	}

	public void setUploadURI(URI uploadURI) {
		this.uploadURI = uploadURI;
	}

	public Object getPhysicalBlob() {
		return physicalBlob;
	}

	public void setPhysicalBlob(Object physicalBlob) {
		this.physicalBlob = physicalBlob;
	}

	public Object getUploadedBlob() {
		return uploadedBlob;
	}

	public void setUploadedBlob(Object uploadedBlob) {
		this.uploadedBlob = uploadedBlob;
	}

	public String getsCType() {
		return sCType;
	}

	public void setsCType(String sCType) {
		this.sCType = sCType;
	}
	
}
