//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.12.26 at 04:34:08 AM EET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.example.org/PersistentStorageManifest", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package fci.cu.std.paas.api.xml.manifest;
