//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.12.26 at 04:34:08 AM EET 
//


package fci.cu.std.paas.api.xml.manifest;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for persistent_storage_service_manifest complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="persistent_storage_service_manifest">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="storage_service_account" type="{http://www.example.org/PersistentStorageManifest}storage_service_account"/>
 *         &lt;element name="container" type="{http://www.example.org/PersistentStorageManifest}container"/>
 *         &lt;element name="blob" type="{http://www.example.org/PersistentStorageManifest}blob"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "persistent_storage_service_manifest", propOrder = {
    "description",
    "storageServiceAccount",
    "container",
    "blob"
})
public class PersistentStorageServiceManifest {

    @XmlElement(required = true)
    protected String description;
    @XmlElement(name = "storage_service_account", required = true)
    protected StorageServiceAccount storageServiceAccount;
    @XmlElement(required = true)
    protected Container container;
    @XmlElement(required = true)
    protected Blob blob;

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the storageServiceAccount property.
     * 
     * @return
     *     possible object is
     *     {@link StorageServiceAccount }
     *     
     */
    public StorageServiceAccount getStorageServiceAccount() {
        return storageServiceAccount;
    }

    /**
     * Sets the value of the storageServiceAccount property.
     * 
     * @param value
     *     allowed object is
     *     {@link StorageServiceAccount }
     *     
     */
    public void setStorageServiceAccount(StorageServiceAccount value) {
        this.storageServiceAccount = value;
    }

    /**
     * Gets the value of the container property.
     * 
     * @return
     *     possible object is
     *     {@link Container }
     *     
     */
    public Container getContainer() {
        return container;
    }

    /**
     * Sets the value of the container property.
     * 
     * @param value
     *     allowed object is
     *     {@link Container }
     *     
     */
    public void setContainer(Container value) {
        this.container = value;
    }

    /**
     * Gets the value of the blob property.
     * 
     * @return
     *     possible object is
     *     {@link Blob }
     *     
     */
    public Blob getBlob() {
        return blob;
    }

    /**
     * Sets the value of the blob property.
     * 
     * @param value
     *     allowed object is
     *     {@link Blob }
     *     
     */
    public void setBlob(Blob value) {
        this.blob = value;
    }

}
